Add check for tag existing before publishing pod

diff --git a/.github/workflows/ios-release.yml b/.github/workflows/ios-release.yml
--- a/.github/workflows/ios-release.yml
+++ b/.github/workflows/ios-release.yml
@@ -208,6 +208,14 @@ jobs:
       run: |
         set -eo pipefail
 
+        # Check if the tag exists using gh
+        if ! gh api repos/${GITHUB_REPOSITORY}/git/refs/tags/${TAG} > /dev/null 2>&1; then
+          echo "Error: Tag '${TAG}' does not exist."
+          exit 1
+        fi
+
+        echo "Tag '${TAG}' exists."
+
         # Split the input string into an array using comma as delimiter
         IFS=',' read -ra LIBS <<< "${POD_PUBLISH_EXTENSIONS}"
 
